baseURL = 'https://francoacg.com/'
languageCode = 'en-us'
title = "Franco's website"
theme = 'etch'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"

